### ISSUE TITLE
Difficult to read inactive tab names

### ISSUE THREAD

**Issue by aldis-ameriks** [blueshirts/darcula#13]
![image](https://user-images.githubusercontent.com/25861734/39660787-735ce8b4-504e-11e8-9e7c-d9b367ecd76e.png)

Tab names for inactive tabs are white on a gray background, difficult to read.

➜  ~ nvim -v
NVIM v0.2.2
Build type: Release
LuaJIT 2.0.5
Compilation: /usr/local/Homebrew/Library/Homebrew/shims/super/clang -Wconversion -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DNDEBUG -DMIN_LOG_LEVEL=3 -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -I/tmp/neovim-20180209-92407-udkzoo/neovim-0.2.2/build/config -I/tmp/neovim-20180209-92407-udkzoo/neovim-0.2.2/src -I/usr/local/include -I/usr/local/include -I/usr/local/include -I/usr/local/include -I/usr/local/include -I/usr/local/include -I/usr/local/opt/gettext/include -I/usr/include -I/tmp/neovim-20180209-92407-udkzoo/neovim-0.2.2/build/src/nvim/auto -I/tmp/neovim-20180209-92407-udkzoo/neovim-0.2.2/build/include
Compiled by brew@HighSierra.local

**Comment by blueshirts** [comment]
I the issue in the screen shot though I am not sure how to reproduce it locally.   I typically use MacVim.  How do I bring up this view?

**Comment by aldis-ameriks** [comment]
I'm using neovim inside iTerm2 with xterm-256color terminal colors.
New tabs in vim (nvim) can be opened using :tabnew command.

EDIT:
I checked briefly, and it seems that these colors are missing from the darcula.vim
```
TabLineFill
TabLine
TabLineSel
```

**Comment by blueshirts** [comment]
Suggestions on colors or names of other color attributes to match?  Either that or send a PR.

**Comment by aldis-ameriks** [comment]
Opened a PR #14 for adding colors for tabs.

**Comment by thosakwe** [comment]
Using Vim 8, getting the same result (using the latest version of `darcula`). What fixes it for me is:

```vim
" hi TabLineFill ctermfg=146 ctermbg=16 cterm=NONE guifg=#a9b7c6 guibg=#2b2b2b gui=undercurl
hi TabLine ctermfg=146 ctermbg=16 cterm=NONE guifg=#a9b7c6 guibg=#2b2b2b gui=undercurl
hi TabLineSel ctermfg=146 ctermbg=59 cterm=NONE guifg=#a9b7c6 guibg=#515658 gui=undercurl
```

Similar lines to these are at the bottom of `darcula.vim`, but with `gui=NONE` (not 100% sure why `NONE` is used here, haven't written a highlighter before).

Uncommenting the first of the above lines will cause the tab bar itself to be colored, which isn't consistent with Vim's default color scheme.

Changed it in a fork. If you think it's worth a PR, LMK: https://github.com/thosakwe/darcula
