### ISSUE TITLE
JS file - "function" in GUI mode has red background

### ISSUE THREAD

**Issue by yyyar** [blueshirts/darcula#2]
When editing JS code in GUI mode, 'function' word has annoying red background.
It's caused by guibg=red in darcula.vim. Seems mistake.

line 96:

```
 hi javaScriptFunction ctermfg=222 ctermbg=NONE cterm=NONE guifg=#d58b48 guibg=red gui=bold
```

Could you please fix it? (i.e. guibg=NONE).

Thanks!

**Comment by blueshirts** [comment]
Should be fixed.  Was trying to see the highlight though didn't show up with my distribution (Janus).
