### ISSUE TITLE
Autocomplete popup background is the same as editor background

### ISSUE THREAD

**Issue by nothingelsematters7** [blueshirts/darcula#3]
So it's too hard to distinguish them.
You can see it here [Screenshot](http://cl.ly/0H1Q0n3C1s3s)

**Comment by blueshirts** [comment]
Unsure if the changes help though I did some updates.

**Comment by nothingelsematters7** [comment]
@blueshirts no, problem stays the same

**Comment by blueshirts** [comment]
I changed the background color of the popup slightly.  Do you not see a difference?
