### ISSUE TITLE
Doesn't work inside tmux

### ISSUE THREAD

**Issue by nxvl** [blueshirts/darcula#7]
1. Open tmux in iterm2
2. Open a file using vim
3. No colors are shown.

Works fine if outside tmux.

**Comment by blueshirts** [comment]
Doesn't sound like a color scheme issue.  Sounds like an issue with tmux and VIM.

http://stackoverflow.com/questions/10158508/lose-vim-colorscheme-in-tmux-mode

I am sure there are other threads.

**Comment by blueshirts** [comment]
Re-open if not resolved.
