### ISSUE TITLE
Vundle

### ISSUE THREAD

**Issue by Notaduck** [blueshirts/darcula#9]
I tried to install this with vundle, but i keep getting the following error

```
Error detected while processing /home/danielga/.vimrc:
line    5:
E185: Cannot find color scheme 'darcula'

```

**Comment by blueshirts** [comment]
I took a look a most of the other vim color schemes and the standard installation is to just place it in the .vim/colors directory.  I removed the documentation around pathogen, etc.

**Comment by blueshirts** [comment]
That said I think it should work.  You'll get that error when you open vim with the Plugin line added until you run :PluginInstall.  I saw the same error.

```
" add to .vimrc
Plugin 'blueshirts/darcula'
```

From vim: 

```
:PluginInstall
```
